# Generated by Django 3.0.5 on 2020-04-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
    ]
